NON_VUE_COMPONENTS = ["div", "container", "header"]
# used by studio components internally so needs to be included in the build
DEFAULT_COMPONENTS = ["FeatherIcon"]

# All standard component names (frappe-ui + studio built-in) used for conflict detection
STANDARD_COMPONENT_NAMES = {
	# frappe-ui
	"Alert",
	"Autocomplete",
	"Avatar",
	"Badge",
	"Button",
	"Breadcrumbs",
	"Card",
	"Checkbox",
	"Calendar",
	"Combobox",
	"DatePicker",
	"TimePicker",
	"DateTimePicker",
	"DateRangePicker",
	"MonthPicker",
	"Dialog",
	"Divider",
	"Dropdown",
	"ErrorMessage",
	"FeatherIcon",
	"FileUploader",
	"FormLabel",
	"FormControl",
	"ListView",
	"MultiSelect",
	"Progress",
	"Rating",
	"Select",
	"Sidebar",
	"Switch",
	"Tabs",
	"TabButtons",
	"Textarea",
	"TextInput",
	"TextEditor",
	"Tooltip",
	"Tree",
	"AxisChart",
	"NumberChart",
	"DonutChart",
	# frappe
	"Filter",
	"Link",
	# studio built-in
	"Container",
	"FitContainer",
	"Repeater",
	"HTML",
	"Header",
	"SplitView",
	"AvatarCard",
	"CardList",
	"Audio",
	"ImageView",
	"TextBlock",
	"AppHeader",
	"BottomTabs",
	"MarkdownEditor",
}
